### ISSUE TITLE
Make enemy bullet patterns

### ISSUE THREAD

**Issue by Johndayll** [sitiom/Debugmancer#5]
There are 5 patterns:
 **Normal fire**
- Fires every 1-2 seconds

**Rapid fire**
- Fires for 3 seconds straight
- 2- 4 second cooldown

**All around the enemy**
- Bullets spawn around the enemy
- 2-4 second cooldown

 **Shotgun**
- V shape
- 2-4 second cooldown

**Rambo**
- Projectiles are spread left and right
- 2-4 second cooldown

**Comment by sitiom** [comment]
Completed by #9
